### ISSUE TITLE
Assignment 9-4 - Teamwork

### ISSUE THREAD

**Issue by ambethia** [josh-wykell/assignments#42]
# Week 9 - Assignment 4

## Working as a Team

- [ ] With your 3 other team members: deploy an app you can be proud of. Push it harder and further than projects up until now.

| Red Team | Blue Team |
|----------|-----------|
| Michael  | Derek     |
| Kelly    | Josh      |
| Aaron    | Amie      |
| Duncan   | Bennett   |

**Comment by josh-wykell** [comment]
https://obscure-river-6239.herokuapp.com/
https://github.com/josh-wykell/reddit_clone

We added voting to comments, made comments polymorphic(nesting), added tagging, added admin, and changed the layout a bit as far as how you view links, and what links to what on the home page. Also added previews of images in the index and show pages.

This was the original app

https://github.com/BC3209/TBD
